name: build
on: [push, pull_request]

jobs:
  build:
    name: build (${{ matrix.platform.name }}, ${{ matrix.build-type }}${{ matrix.debug-tools == 'On' && ' + Tools' || '' }})

    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: windows-latest
            name: Windows
          - os: ubuntu-22.04
            name: Linux
          - os: macos-12
            name: MacOS
        build-type: [Debug, Release]
        debug-tools: [On, Off]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev

      - name: Configure CMake
        run: |
          cmake . -DAPORIA_DEBUGTOOLS=${{ matrix.debug-tools }}

      - name: Build
        run: |
          cmake --build . --config ${{ matrix.build-type }} --verbose
