name: emscripten
on: [push, pull_request]

jobs:
  emscripten:
    strategy:
      fail-fast: false

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v11

      - name: Configure CMake
        run: |
          emcmake cmake . -DAPORIA_EMSCRIPTEN=ON

      - name: Build with Emscripten
        run: |
          emmake make
